//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class EspacioEntites : DbContext
{
    public EspacioEntites()
        : base("name=EspacioEntites")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<ALOJAMIENTO> ALOJAMIENTO { get; set; }
    public virtual DbSet<COMUNA> COMUNA { get; set; }
    public virtual DbSet<IMAGENES> IMAGENES { get; set; }
    public virtual DbSet<RESEÑA> RESEÑA { get; set; }
    public virtual DbSet<RESERVA> RESERVA { get; set; }
    public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
    public virtual DbSet<UBICACION> UBICACION { get; set; }
    public virtual DbSet<USUARIO> USUARIO { get; set; }
    public virtual DbSet<ZONA_GEOGRAFICA> ZONA_GEOGRAFICA { get; set; }
    public virtual DbSet<REGION> REGION { get; set; }
    public virtual DbSet<ACTIVIDADES> ACTIVIDADES { get; set; }
}
