//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ACTIVIDADES
{
    public int ID { get; set; }
    public string DESCRIPCION_CORTA { get; set; }
    public string DESCRIPCION_LARGA { get; set; }
    public Nullable<int> ID_UBICACION { get; set; }

    public virtual UBICACION UBICACION { get; set; }
}

public partial class ALOJAMIENTO
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ALOJAMIENTO()
    {
        this.RESERVA = new HashSet<RESERVA>();
        this.IMAGENES = new HashSet<IMAGENES>();
        this.RESEÑA_ALOJAMIENTO = new HashSet<RESEÑA_ALOJAMIENTO>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION_CORTA { get; set; }
    public string DESCRIPCION_LARGA { get; set; }
    public string UBICACION { get; set; }
    public Nullable<double> LATITUD { get; set; }
    public Nullable<double> LONGITUD { get; set; }
    public Nullable<int> ID_COMUNA { get; set; }
    public Nullable<int> BANIOS { get; set; }
    public Nullable<int> DORMITORIOS { get; set; }
    public Nullable<int> VALOR_NOCHE { get; set; }
    public Nullable<int> CANT_MAX_PERSONAS { get; set; }

    public virtual COMUNA COMUNA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RESERVA> RESERVA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<IMAGENES> IMAGENES { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RESEÑA_ALOJAMIENTO> RESEÑA_ALOJAMIENTO { get; set; }
}

public partial class COMUNA
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public COMUNA()
    {
        this.ALOJAMIENTO = new HashSet<ALOJAMIENTO>();
        this.UBICACION = new HashSet<UBICACION>();
        this.USUARIO = new HashSet<USUARIO>();
        this.ZONA_GEOGRAFICA = new HashSet<ZONA_GEOGRAFICA>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public Nullable<int> ID_REGION { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ALOJAMIENTO> ALOJAMIENTO { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UBICACION> UBICACION { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<USUARIO> USUARIO { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ZONA_GEOGRAFICA> ZONA_GEOGRAFICA { get; set; }
    public virtual REGION REGION { get; set; }
}

public partial class IMAGENES
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public IMAGENES()
    {
        this.ALOJAMIENTO = new HashSet<ALOJAMIENTO>();
        this.UBICACION1 = new HashSet<UBICACION>();
        this.ZONA_GEOGRAFICA = new HashSet<ZONA_GEOGRAFICA>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public string TIPO_IMAGEN { get; set; }
    public string RUTA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ALOJAMIENTO> ALOJAMIENTO { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UBICACION> UBICACION1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ZONA_GEOGRAFICA> ZONA_GEOGRAFICA { get; set; }
}

public partial class REGION
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public REGION()
    {
        this.COMUNA = new HashSet<COMUNA>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<COMUNA> COMUNA { get; set; }
}

public partial class RESEÑA_ALOJAMIENTO
{
    public int ID { get; set; }
    public string DESCRIPCION { get; set; }
    public Nullable<System.DateTime> FECHA { get; set; }
    public Nullable<int> ID_USUARIO { get; set; }
    public Nullable<int> ID_ALOJAMIENTO { get; set; }
    public Nullable<double> PUNTUACION { get; set; }

    public virtual ALOJAMIENTO ALOJAMIENTO { get; set; }
    public virtual USUARIO USUARIO { get; set; }
}

public partial class RESEÑA_UBICACION
{
    public int ID { get; set; }
    public string DESCRIPCION { get; set; }
    public Nullable<System.DateTime> FECHA { get; set; }
    public Nullable<int> ID_USUARIO { get; set; }
    public Nullable<int> ID_UBICACION { get; set; }
    public Nullable<double> PUNTUACION { get; set; }

    public virtual ALOJAMIENTO ALOJAMIENTO { get; set; }
    public virtual USUARIO USUARIO { get; set; }
    public virtual UBICACION UBICACION { get; set; }
}

public partial class RESERVA
{
    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public Nullable<System.DateTime> FECHA_INICIO { get; set; }
    public Nullable<System.DateTime> FECHA_TERMINO { get; set; }
    public string COMENTARIO { get; set; }
    public Nullable<int> ID_ALOJAMIENTO { get; set; }
    public Nullable<int> ID_USUARIO { get; set; }
    public Nullable<int> CODIGO_RESERVA { get; set; }
    public Nullable<double> TOTAL { get; set; }

    public virtual ALOJAMIENTO ALOJAMIENTO { get; set; }
    public virtual USUARIO USUARIO { get; set; }
}

public partial class TIPO_USUARIO
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TIPO_USUARIO()
    {
        this.USUARIO = new HashSet<USUARIO>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public string ACCESS_PAGE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<USUARIO> USUARIO { get; set; }
}

public partial class UBICACION
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UBICACION()
    {
        this.IMAGENES = new HashSet<IMAGENES>();
        this.ACTIVIDADES = new HashSet<ACTIVIDADES>();
        this.RESEÑA_UBICACION = new HashSet<RESEÑA_UBICACION>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION_CORTA { get; set; }
    public string DESCRIPCION_LARGA { get; set; }
    public Nullable<int> ID_COMUNA { get; set; }
    public Nullable<int> ID_ZONA { get; set; }
    public Nullable<double> LATITUD { get; set; }
    public Nullable<double> LONGITUD { get; set; }

    public virtual COMUNA COMUNA { get; set; }
    public virtual ZONA_GEOGRAFICA ZONA_GEOGRAFICA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<IMAGENES> IMAGENES { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ACTIVIDADES> ACTIVIDADES { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RESEÑA_UBICACION> RESEÑA_UBICACION { get; set; }
}

public partial class USUARIO
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public USUARIO()
    {
        this.RESERVA = new HashSet<RESERVA>();
        this.RESEÑA_ALOJAMIENTO = new HashSet<RESEÑA_ALOJAMIENTO>();
        this.RESEÑA_UBICACION = new HashSet<RESEÑA_UBICACION>();
    }

    public int ID { get; set; }
    public string EMAIL { get; set; }
    public string PASSWORD { get; set; }
    public string NOMBRE { get; set; }
    public string SEG_NOMBRE { get; set; }
    public string APELLIDO { get; set; }
    public string SEG_APELLIDO { get; set; }
    public string IDENTIFICADOR { get; set; }
    public Nullable<int> TELEFONO { get; set; }
    public string DIRECCION { get; set; }
    public Nullable<int> ID_COMUNA { get; set; }
    public Nullable<int> ID_TIPO_USUARIO { get; set; }
    public string RUTA_IMAGEN { get; set; }

    public virtual COMUNA COMUNA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RESERVA> RESERVA { get; set; }
    public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RESEÑA_ALOJAMIENTO> RESEÑA_ALOJAMIENTO { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RESEÑA_UBICACION> RESEÑA_UBICACION { get; set; }
}

public partial class ZONA_GEOGRAFICA
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ZONA_GEOGRAFICA()
    {
        this.UBICACION = new HashSet<UBICACION>();
        this.IMAGENES = new HashSet<IMAGENES>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION_CORTA { get; set; }
    public string DESCRIPCION_LARGA { get; set; }
    public Nullable<int> ID_COMUNA { get; set; }

    public virtual COMUNA COMUNA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UBICACION> UBICACION { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<IMAGENES> IMAGENES { get; set; }
}
